"""
Image Generation Service
Uses OpenAI DALL-E (requires paid key) OR Pollinations.ai (100% FREE, no key needed).
"""
import requests
import base64
from config import Config


class ImageService:
    def __init__(self, api_key: str = ""):
        self.api_key = api_key or Config.OPENAI_API_KEY

    def is_configured(self) -> bool:
        # Pollinations is always available (free, no key)
        return True

    def get_available_models(self):
        return [
            {"id": "pollinations",   "name": "Pollinations AI – FREE (no key needed)"},
            {"id": "dall-e-3",       "name": "DALL-E 3 (requires OpenAI key)"},
            {"id": "dall-e-2",       "name": "DALL-E 2 (requires OpenAI key)"},
        ]

    # ── Pollinations FREE image gen ────────────────────────────────────────
    def _pollinations(self, prompt: str, size: str = "1024x1024"):
        import urllib.parse
        width, height = (size.split("x") + ["1024", "1024"])[:2]
        encoded = urllib.parse.quote(prompt)
        url = f"https://image.pollinations.ai/prompt/{encoded}?width={width}&height={height}&nologo=true"
        return {
            "success": True,
            "image_url": url,
            "model": "pollinations",
            "note": "Generated by Pollinations.ai (FREE)",
        }

    # ── DALL-E ─────────────────────────────────────────────────────────────
    def _dalle(self, prompt: str, model: str, size: str, quality: str):
        if not self.api_key:
            return {
                "success": False,
                "error": "OpenAI API key required for DALL-E. Using Pollinations (free) instead. Add your key in ⚙️ Settings.",
            }
        url = "https://api.openai.com/v1/images/generations"
        headers = {"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
        payload = {
            "model": model,
            "prompt": prompt,
            "n": 1,
            "size": size,
        }
        if model == "dall-e-3":
            payload["quality"] = quality
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=60)
            r.raise_for_status()
            image_url = r.json()["data"][0]["url"]
            return {"success": True, "image_url": image_url, "model": model}
        except requests.exceptions.HTTPError as e:
            return {"success": False, "error": f"DALL-E error: {e.response.text}"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    # ── public API ─────────────────────────────────────────────────────────
    def generate_image(self, prompt: str, model: str = "pollinations",
                       size: str = "1024x1024", quality: str = "standard"):
        if model == "pollinations" or not self.api_key:
            return self._pollinations(prompt, size)
        return self._dalle(prompt, model, size, quality)
